name: Deploy to PyPi

on:
  push:
    tags:
       - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Test
      uses: nuuuwan/python-repo-test@v1

    - name: Build package
      run: |
        export PYTHONPATH="$PYTHONPATH:./src"
        python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
