name: Test (on Push)

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Set GitHub User
      run: |
        git config --global user.name "${{ secrets.GIT_USER_NAME  }}"
        git config --global user.email "${{ secrets.GIT_USER_EMAIL  }}"

    - name: Test
      uses: nuuuwan/python-repo-test@v1
